// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaWeXJFJ95YXWZ-Q28lIDIWeFf39_1D0',
    appId: '1:468377997271:web:bb26bd71deadd1d5594592',
    messagingSenderId: '468377997271',
    projectId: 'project-prm393',
    authDomain: 'project-prm393.firebaseapp.com',
    databaseURL: 'https://project-prm393-default-rtdb.firebaseio.com',
    storageBucket: 'project-prm393.firebasestorage.app',
    measurementId: 'G-GTTEHM8CJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfff7BuAUyhvwiaOJrwMBHbyApX8nLx6w',
    appId: '1:468377997271:android:e90ddeb62223fc54594592',
    messagingSenderId: '468377997271',
    projectId: 'project-prm393',
    databaseURL: 'https://project-prm393-default-rtdb.firebaseio.com',
    storageBucket: 'project-prm393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK22S0aVI0MQQlK6JGnCvSMn06a8i1BY0',
    appId: '1:468377997271:ios:10742af049840d19594592',
    messagingSenderId: '468377997271',
    projectId: 'project-prm393',
    databaseURL: 'https://project-prm393-default-rtdb.firebaseio.com',
    storageBucket: 'project-prm393.firebasestorage.app',
    iosClientId: '468377997271-4qi6glh0103g0la7horfkht2u6cvdken.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPrm393',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK22S0aVI0MQQlK6JGnCvSMn06a8i1BY0',
    appId: '1:468377997271:ios:10742af049840d19594592',
    messagingSenderId: '468377997271',
    projectId: 'project-prm393',
    databaseURL: 'https://project-prm393-default-rtdb.firebaseio.com',
    storageBucket: 'project-prm393.firebasestorage.app',
    iosClientId: '468377997271-4qi6glh0103g0la7horfkht2u6cvdken.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPrm393',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzaWeXJFJ95YXWZ-Q28lIDIWeFf39_1D0',
    appId: '1:468377997271:web:0ccb8e980529072f594592',
    messagingSenderId: '468377997271',
    projectId: 'project-prm393',
    authDomain: 'project-prm393.firebaseapp.com',
    databaseURL: 'https://project-prm393-default-rtdb.firebaseio.com',
    storageBucket: 'project-prm393.firebasestorage.app',
    measurementId: 'G-1PJKQ6CC43',
  );

}